Vagrant.configure("2") do |config|
  config.vm.define :jenkinscapistrano do |jc|
      jc.vm.box = "percyperezd/JenkinsCapistranoV2"
      jc.vm.box_version = "0.0.2"
      jc.vm.hostname = "jenkinscapistrano"
      jc.vm.network :private_network, ip: "172.10.11.10"
      jc.vm.network "forwarded_port", guest: 8080, host: 8080
      jc.vm.provision "shell", :path => "extra_jenkins.sh", :name => "Settings keys for jenkins"
  end
  config.vm.define :victim do |v|
    v.vm.box = "percyperezd/oraclelinux6"
    v.vm.box_version =  "1.0.0"
    v.vm.hostname = "victim"
    v.vm.network :private_network, ip: "172.10.11.4"
    v.vm.provision "shell", :path => "extra_victim.sh", :name => "Settings keys for victim"
  end
  
end
